package u1171639.lms.main.java.corba;


/**
* u1171639/lms/main/java/corba/LMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/lms/main/resources/idl/LMS.idl
* Friday, 3 April 2015 23:06:49 o'clock BST
*/

public interface LMS extends LMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LMS
