package u1171639.lms.main.java.corba;


/**
* u1171639/lms/main/java/corba/LMS_RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/lms/main/resources/idl/LMS_RMC.idl
* Wednesday, 22 April 2015 16:43:07 o'clock BST
*/

public interface LMS_RMCOperations 
{
  u1171639.lms.main.java.corba.Locality getLocalityInfo ();
} // interface LMS_RMCOperations
