package u1171639.lms.main.java.corba;


/**
* u1171639/lms/main/java/corba/LMS_RMCPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/lms/main/resources/idl/LMS_RMC.idl
* Sunday, 5 April 2015 01:16:34 o'clock BST
*/

public abstract class LMS_RMCPOA extends org.omg.PortableServer.Servant
 implements u1171639.lms.main.java.corba.LMS_RMCOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:lms_rmc/LMS_RMC:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LMS_RMC _this() 
  {
    return LMS_RMCHelper.narrow(
    super._this_object());
  }

  public LMS_RMC _this(org.omg.CORBA.ORB orb) 
  {
    return LMS_RMCHelper.narrow(
    super._this_object(orb));
  }


} // class LMS_RMCPOA
