package u1171639.lms.main.java.corba;


/**
* u1171639/lms/main/java/corba/LMS_Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/lms/main/resources/idl/LMS_Sensor.idl
* Wednesday, 22 April 2015 16:43:07 o'clock BST
*/

public interface LMS_Sensor extends LMS_SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LMS_Sensor
