package u1171639.lms.main.java.corba;


/**
* u1171639/lms/main/java/corba/LMS_RMC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/lms/main/resources/idl/LMS_RMC.idl
* Sunday, 5 April 2015 01:16:34 o'clock BST
*/

public interface LMS_RMC extends LMS_RMCOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LMS_RMC
