package u1171639.lms.main.java.corba;

/**
* u1171639/lms/main/java/corba/LMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/lms/main/resources/idl/LMS.idl
* Friday, 3 April 2015 22:51:14 o'clock BST
*/

public final class LMSHolder implements org.omg.CORBA.portable.Streamable
{
  public u1171639.lms.main.java.corba.LMS value = null;

  public LMSHolder ()
  {
  }

  public LMSHolder (u1171639.lms.main.java.corba.LMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = u1171639.lms.main.java.corba.LMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    u1171639.lms.main.java.corba.LMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return u1171639.lms.main.java.corba.LMSHelper.type ();
  }

}
