package u1171639.lms.main.java.corba;


/**
* u1171639/lms/main/java/corba/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS.idl
* Friday, 3 April 2015 19:07:01 o'clock BST
*/

public interface LMSOperations 
{
  void raiseAlarm (String zone);
  void register (String ior, String zone);
} // interface LMSOperations
