package u1171639.lms.main.java.corba;


/**
* u1171639/lms/main/java/corba/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/lms/main/resources/idl/LMS.idl
* Tuesday, 21 April 2015 16:11:15 o'clock BST
*/

public interface LMSOperations 
{
  void raiseAlarm (String zone);
  void register (String ior, String zone);
} // interface LMSOperations
