package u1171639.lms.main.java.corba;


/**
* u1171639/lms/main/java/corba/Locality.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/lms/main/resources/idl/LMS_RMC.idl
* Wednesday, 22 April 2015 16:43:07 o'clock BST
*/

public final class Locality implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public u1171639.lms.main.java.corba.Zone zones[] = null;

  public Locality ()
  {
  } // ctor

  public Locality (String _name, u1171639.lms.main.java.corba.Zone[] _zones)
  {
    name = _name;
    zones = _zones;
  } // ctor

} // class Locality
