package u1171639.rmc.main.java.corba;

/**
* u1171639/rmc/main/java/corba/RMCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/rmc/main/resources/idl/RMC.idl
* Tuesday, 21 April 2015 16:11:15 o'clock BST
*/

public final class RMCHolder implements org.omg.CORBA.portable.Streamable
{
  public u1171639.rmc.main.java.corba.RMC value = null;

  public RMCHolder ()
  {
  }

  public RMCHolder (u1171639.rmc.main.java.corba.RMC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = u1171639.rmc.main.java.corba.RMCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    u1171639.rmc.main.java.corba.RMCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return u1171639.rmc.main.java.corba.RMCHelper.type ();
  }

}
