package u1171639.rmc.main.java.corba;


/**
* u1171639/rmc/main/java/corba/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RMC.idl
* Friday, 3 April 2015 19:52:12 o'clock BST
*/

public interface RMCOperations 
{
  void raiseAlarm ();
} // interface RMCOperations
