package u1171639.rmc.main.java.corba;


/**
* u1171639/rmc/main/java/corba/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/rmc/main/resources/idl/RMC.idl
* Sunday, 5 April 2015 01:16:34 o'clock BST
*/

public interface RMCOperations 
{
  void raiseAlarm ();
  void register (String ior, String locality);
} // interface RMCOperations
