package u1171639.shared.main.java.corba.sensor;


/**
* u1171639/shared/main/java/corba/sensor/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sensor.idl
* Thursday, 9 April 2015 17:54:36 o'clock BST
*/

public interface SensorOperations 
{
  boolean isAlarmRaised ();
  void activate ();
  void deactivate ();
  boolean isActive ();
} // interface SensorOperations
