package u1171639.shared.main.java.corba.sensor;


/**
* u1171639/shared/main/java/corba/sensor/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sensor.idl
* Monday, 20 April 2015 23:09:46 o'clock BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
