package u1171639.shared.main.java.corba.sensor;


/**
* u1171639/shared/main/java/corba/sensor/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sensor.idl
* Thursday, 30 April 2015 10:50:00 o'clock BST
*/

public interface SensorOperations 
{
  boolean isAlarmRaised ();
  void activate ();
  void deactivate ();
  boolean isActive ();
} // interface SensorOperations
