module lms_rmc {
	struct CorbaLogItem {
		string event;
		string message;
	};
	
	struct CorbaSensor {
		string id;
	};

	struct CorbaZone {
		string name;
		boolean alarmRaised;
		sequence<CorbaSensor> sensors;
	};
	
	struct CorbaLocality {
		string name;
		sequence<CorbaZone> zones;
	};
	
	struct CorbaLog {
		sequence<CorbaLogItem> logItems;
	};
	
	interface LMS_RMC {
		CorbaLocality getZoneUpdates();
		CorbaLog getLog();
	};
};