#include <Models.idl>

module lms_rmc {

	interface LMS_RMC {
		models::CorbaModel_Locality getZoneUpdates();
		models::CorbaModel_Log getLog();
		boolean activateSensor(in string zoneName, in string sensorName);
		boolean deactivateSensor(in string zoneName, in string sensorName);
		boolean setWarningThreshold(in string zoneName, in string sensorName, in double threshold);
		double getSensorReading(in string zoneName, in string sensorName);
	};
	
};