module sensor {
	interface Sensor {
		boolean isAlarmRaised();
		boolean activate();
		boolean deactivate();
		boolean isActive();
		double getThreshold();
		boolean setThreshold(in double threshold);
	};
};