package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/_LMS_RMCStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Friday, 10 April 2015 14:13:12 o'clock BST
*/

public class _LMS_RMCStub extends org.omg.CORBA.portable.ObjectImpl implements u1171639.shared.main.java.corba.lms_rmc.LMS_RMC
{

  public u1171639.shared.main.java.corba.lms_rmc.CorbaLocality getZoneUpdates ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getZoneUpdates", true);
                $in = _invoke ($out);
                u1171639.shared.main.java.corba.lms_rmc.CorbaLocality $result = u1171639.shared.main.java.corba.lms_rmc.CorbaLocalityHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getZoneUpdates (        );
            } finally {
                _releaseReply ($in);
            }
  } // getZoneUpdates

  public u1171639.shared.main.java.corba.lms_rmc.CorbaLog getLog ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLog", true);
                $in = _invoke ($out);
                u1171639.shared.main.java.corba.lms_rmc.CorbaLog $result = u1171639.shared.main.java.corba.lms_rmc.CorbaLogHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLog (        );
            } finally {
                _releaseReply ($in);
            }
  } // getLog

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:lms_rmc/LMS_RMC:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _LMS_RMCStub
