package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/CorbaLog.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Friday, 10 April 2015 14:13:12 o'clock BST
*/

public final class CorbaLog implements org.omg.CORBA.portable.IDLEntity
{
  public u1171639.shared.main.java.corba.lms_rmc.CorbaLogItem logItems[] = null;

  public CorbaLog ()
  {
  } // ctor

  public CorbaLog (u1171639.shared.main.java.corba.lms_rmc.CorbaLogItem[] _logItems)
  {
    logItems = _logItems;
  } // ctor

} // class CorbaLog
