package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/CorbaZone.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Thursday, 9 April 2015 17:54:36 o'clock BST
*/

public final class CorbaZone implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public boolean alarmRaised = false;

  public CorbaZone ()
  {
  } // ctor

  public CorbaZone (String _name, boolean _alarmRaised)
  {
    name = _name;
    alarmRaised = _alarmRaised;
  } // ctor

} // class CorbaZone
