package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/CorbaZone.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Friday, 10 April 2015 14:13:12 o'clock BST
*/

public final class CorbaZone implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public boolean alarmRaised = false;
  public u1171639.shared.main.java.corba.lms_rmc.CorbaSensor sensors[] = null;

  public CorbaZone ()
  {
  } // ctor

  public CorbaZone (String _name, boolean _alarmRaised, u1171639.shared.main.java.corba.lms_rmc.CorbaSensor[] _sensors)
  {
    name = _name;
    alarmRaised = _alarmRaised;
    sensors = _sensors;
  } // ctor

} // class CorbaZone
