package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/CorbaLMSLog.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Thursday, 9 April 2015 19:47:15 o'clock BST
*/

public final class CorbaLMSLog implements org.omg.CORBA.portable.IDLEntity
{
  public u1171639.shared.main.java.corba.lms_rmc.CorbaLogItem logItems[] = null;

  public CorbaLMSLog ()
  {
  } // ctor

  public CorbaLMSLog (u1171639.shared.main.java.corba.lms_rmc.CorbaLogItem[] _logItems)
  {
    logItems = _logItems;
  } // ctor

} // class CorbaLMSLog
