package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/CorbaSensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Friday, 10 April 2015 14:13:12 o'clock BST
*/

public final class CorbaSensor implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;

  public CorbaSensor ()
  {
  } // ctor

  public CorbaSensor (String _id)
  {
    id = _id;
  } // ctor

} // class CorbaSensor
