package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/LMS_RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Thursday, 30 April 2015 13:41:00 o'clock BST
*/

public interface LMS_RMCOperations 
{
  u1171639.shared.main.java.corba.models.CorbaModel_Locality getZoneUpdates ();
  u1171639.shared.main.java.corba.models.CorbaModel_Log getLog ();
} // interface LMS_RMCOperations
