package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/LMS_RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Thursday, 9 April 2015 17:54:36 o'clock BST
*/

public interface LMS_RMCOperations 
{
  u1171639.shared.main.java.corba.lms_rmc.CorbaLocality getLocalityInfo ();
  u1171639.shared.main.java.corba.lms_rmc.CorbaLMSLog getLogs ();
} // interface LMS_RMCOperations
