package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/LMS_RMCHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Thursday, 30 April 2015 21:03:57 o'clock BST
*/

abstract public class LMS_RMCHelper
{
  private static String  _id = "IDL:lms_rmc/LMS_RMC:1.0";

  public static void insert (org.omg.CORBA.Any a, u1171639.shared.main.java.corba.lms_rmc.LMS_RMC that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static u1171639.shared.main.java.corba.lms_rmc.LMS_RMC extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (u1171639.shared.main.java.corba.lms_rmc.LMS_RMCHelper.id (), "LMS_RMC");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static u1171639.shared.main.java.corba.lms_rmc.LMS_RMC read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LMS_RMCStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, u1171639.shared.main.java.corba.lms_rmc.LMS_RMC value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static u1171639.shared.main.java.corba.lms_rmc.LMS_RMC narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof u1171639.shared.main.java.corba.lms_rmc.LMS_RMC)
      return (u1171639.shared.main.java.corba.lms_rmc.LMS_RMC)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      u1171639.shared.main.java.corba.lms_rmc._LMS_RMCStub stub = new u1171639.shared.main.java.corba.lms_rmc._LMS_RMCStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static u1171639.shared.main.java.corba.lms_rmc.LMS_RMC unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof u1171639.shared.main.java.corba.lms_rmc.LMS_RMC)
      return (u1171639.shared.main.java.corba.lms_rmc.LMS_RMC)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      u1171639.shared.main.java.corba.lms_rmc._LMS_RMCStub stub = new u1171639.shared.main.java.corba.lms_rmc._LMS_RMCStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
