package u1171639.shared.main.java.corba.lms_rmc;


/**
* u1171639/shared/main/java/corba/lms_rmc/LMS_RMCPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_RMC.idl
* Saturday, 18 April 2015 18:41:22 o'clock BST
*/

public abstract class LMS_RMCPOA extends org.omg.PortableServer.Servant
 implements u1171639.shared.main.java.corba.lms_rmc.LMS_RMCOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getZoneUpdates", new java.lang.Integer (0));
    _methods.put ("getLog", new java.lang.Integer (1));
    _methods.put ("activateSensor", new java.lang.Integer (2));
    _methods.put ("deactivateSensor", new java.lang.Integer (3));
    _methods.put ("setWarningThreshold", new java.lang.Integer (4));
    _methods.put ("getSensorReading", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // lms_rmc/LMS_RMC/getZoneUpdates
       {
         u1171639.shared.main.java.corba.models.CorbaModel_Locality $result = null;
         $result = this.getZoneUpdates ();
         out = $rh.createReply();
         u1171639.shared.main.java.corba.models.CorbaModel_LocalityHelper.write (out, $result);
         break;
       }

       case 1:  // lms_rmc/LMS_RMC/getLog
       {
         u1171639.shared.main.java.corba.models.CorbaModel_Log $result = null;
         $result = this.getLog ();
         out = $rh.createReply();
         u1171639.shared.main.java.corba.models.CorbaModel_LogHelper.write (out, $result);
         break;
       }

       case 2:  // lms_rmc/LMS_RMC/activateSensor
       {
         String zoneName = in.read_string ();
         String sensorName = in.read_string ();
         boolean $result = false;
         $result = this.activateSensor (zoneName, sensorName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // lms_rmc/LMS_RMC/deactivateSensor
       {
         String zoneName = in.read_string ();
         String sensorName = in.read_string ();
         boolean $result = false;
         $result = this.deactivateSensor (zoneName, sensorName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // lms_rmc/LMS_RMC/setWarningThreshold
       {
         String zoneName = in.read_string ();
         String sensorName = in.read_string ();
         double threshold = in.read_double ();
         boolean $result = false;
         $result = this.setWarningThreshold (zoneName, sensorName, threshold);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // lms_rmc/LMS_RMC/getSensorReading
       {
         String zoneName = in.read_string ();
         String sensorName = in.read_string ();
         double $result = (double)0;
         $result = this.getSensorReading (zoneName, sensorName);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:lms_rmc/LMS_RMC:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LMS_RMC _this() 
  {
    return LMS_RMCHelper.narrow(
    super._this_object());
  }

  public LMS_RMC _this(org.omg.CORBA.ORB orb) 
  {
    return LMS_RMCHelper.narrow(
    super._this_object(orb));
  }


} // class LMS_RMCPOA
