package u1171639.shared.main.java.corba.lms_sensor;


/**
* u1171639/shared/main/java/corba/lms_sensor/LMS_Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_Sensor.idl
* Monday, 20 April 2015 23:09:46 o'clock BST
*/

public interface LMS_Sensor extends LMS_SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LMS_Sensor
