package u1171639.shared.main.java.corba.lms_sensor;


/**
* u1171639/shared/main/java/corba/lms_sensor/LMS_SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_Sensor.idl
* Thursday, 9 April 2015 17:54:36 o'clock BST
*/

public interface LMS_SensorOperations 
{
  void raiseAlarm (String zone);
  void register (String ior, String zone);
} // interface LMS_SensorOperations
