package u1171639.sensor.main.java.corba.lms_sensor;

/**
* u1171639/sensor/main/java/corba/lms_sensor/LMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_Sensor.idl
* Wednesday, 1 April 2015 01:57:01 o'clock BST
*/

public final class LMSHolder implements org.omg.CORBA.portable.Streamable
{
  public u1171639.sensor.main.java.corba.lms_sensor.LMS value = null;

  public LMSHolder ()
  {
  }

  public LMSHolder (u1171639.sensor.main.java.corba.lms_sensor.LMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = u1171639.sensor.main.java.corba.lms_sensor.LMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    u1171639.sensor.main.java.corba.lms_sensor.LMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return u1171639.sensor.main.java.corba.lms_sensor.LMSHelper.type ();
  }

}
