package u1171639.sensor.main.java.corba.lms_sensor;


/**
* u1171639/sensor/main/java/corba/lms_sensor/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_Sensor.idl
* Wednesday, 1 April 2015 01:57:01 o'clock BST
*/

public interface LMSOperations 
{
  void raiseAlarm ();
} // interface LMSOperations
