package u1171639.sensor.main.java.corba.sensor;


/**
* u1171639/sensor/main/java/corba/sensor/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sensor.idl
* Wednesday, 1 April 2015 01:49:03 o'clock BST
*/

public interface SensorOperations 
{
  String hello ();
} // interface SensorOperations
