package u1171639.sensor.main.java.corba.sensor;


/**
* u1171639/sensor/main/java/corba/sensor/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sensor.idl
* Wednesday, 1 April 2015 01:49:03 o'clock BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
