package u1171639.shared.main.java.corba.rmc;


/**
* u1171639/shared/main/java/corba/rmc/RMC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RMC.idl
* Thursday, 9 April 2015 19:47:15 o'clock BST
*/

public interface RMC extends RMCOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RMC
