package u1171639.shared.main.java.corba.rmc;

/**
* u1171639/shared/main/java/corba/rmc/RMCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RMC.idl
* Thursday, 30 April 2015 10:50:01 o'clock BST
*/

public final class RMCHolder implements org.omg.CORBA.portable.Streamable
{
  public u1171639.shared.main.java.corba.rmc.RMC value = null;

  public RMCHolder ()
  {
  }

  public RMCHolder (u1171639.shared.main.java.corba.rmc.RMC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = u1171639.shared.main.java.corba.rmc.RMCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    u1171639.shared.main.java.corba.rmc.RMCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return u1171639.shared.main.java.corba.rmc.RMCHelper.type ();
  }

}
