package u1171639.shared.main.java.corba.rmc;


/**
* u1171639/shared/main/java/corba/rmc/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RMC.idl
* Monday, 20 April 2015 23:09:47 o'clock BST
*/

public interface RMCOperations 
{
  void raiseAlarm (String locality, String zone);
  void register (String ior, String locality);
  void sensorAdded ();
} // interface RMCOperations
