package u1171639.shared.main.java.corba.rmc;


/**
* u1171639/shared/main/java/corba/rmc/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RMC.idl
* Thursday, 9 April 2015 17:54:36 o'clock BST
*/

public interface RMCOperations 
{
  void raiseAlarm (String locality, String zone);
  void register (String ior, String locality);
} // interface RMCOperations
