package u1171639.lms.main.java.corba.lms;

/**
* u1171639/lms/main/java/corba/lms/LMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS.idl
* Friday, 3 April 2015 15:13:57 o'clock BST
*/

public final class LMSHolder implements org.omg.CORBA.portable.Streamable
{
  public u1171639.lms.main.java.corba.lms.LMS value = null;

  public LMSHolder ()
  {
  }

  public LMSHolder (u1171639.lms.main.java.corba.lms.LMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = u1171639.lms.main.java.corba.lms.LMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    u1171639.lms.main.java.corba.lms.LMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return u1171639.lms.main.java.corba.lms.LMSHelper.type ();
  }

}
