package u1171639.lms.main.java.corba.lms;


/**
* u1171639/lms/main/java/corba/lms/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS.idl
* Friday, 3 April 2015 15:13:57 o'clock BST
*/

public interface LMSOperations 
{
  void raiseAlarm ();
} // interface LMSOperations
