package u1171639.shared.main.java.corba.models;


/**
* u1171639/shared/main/java/corba/models/CorbaModel_LogItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Models.idl
* Thursday, 30 April 2015 10:50:00 o'clock BST
*/

public final class CorbaModel_LogItem implements org.omg.CORBA.portable.IDLEntity
{
  public String event = null;
  public String message = null;

  public CorbaModel_LogItem ()
  {
  } // ctor

  public CorbaModel_LogItem (String _event, String _message)
  {
    event = _event;
    message = _message;
  } // ctor

} // class CorbaModel_LogItem
