package u1171639.shared.main.java.corba.models;


/**
* u1171639/shared/main/java/corba/models/CorbaModel_LogHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Models.idl
* Thursday, 30 April 2015 21:03:57 o'clock BST
*/

abstract public class CorbaModel_LogHelper
{
  private static String  _id = "IDL:models/CorbaModel_Log:1.0";

  public static void insert (org.omg.CORBA.Any a, u1171639.shared.main.java.corba.models.CorbaModel_Log that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static u1171639.shared.main.java.corba.models.CorbaModel_Log extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = u1171639.shared.main.java.corba.models.CorbaModel_LogItemHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "logItems",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (u1171639.shared.main.java.corba.models.CorbaModel_LogHelper.id (), "CorbaModel_Log", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static u1171639.shared.main.java.corba.models.CorbaModel_Log read (org.omg.CORBA.portable.InputStream istream)
  {
    u1171639.shared.main.java.corba.models.CorbaModel_Log value = new u1171639.shared.main.java.corba.models.CorbaModel_Log ();
    int _len0 = istream.read_long ();
    value.logItems = new u1171639.shared.main.java.corba.models.CorbaModel_LogItem[_len0];
    for (int _o1 = 0;_o1 < value.logItems.length; ++_o1)
      value.logItems[_o1] = u1171639.shared.main.java.corba.models.CorbaModel_LogItemHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, u1171639.shared.main.java.corba.models.CorbaModel_Log value)
  {
    ostream.write_long (value.logItems.length);
    for (int _i0 = 0;_i0 < value.logItems.length; ++_i0)
      u1171639.shared.main.java.corba.models.CorbaModel_LogItemHelper.write (ostream, value.logItems[_i0]);
  }

}
