package u1171639.shared.main.java.corba.models;


/**
* u1171639/shared/main/java/corba/models/CorbaModel_Zone.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Models.idl
* Thursday, 30 April 2015 21:03:57 o'clock BST
*/

public final class CorbaModel_Zone implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public boolean alarmRaised = false;
  public u1171639.shared.main.java.corba.models.CorbaModel_Sensor sensors[] = null;

  public CorbaModel_Zone ()
  {
  } // ctor

  public CorbaModel_Zone (String _name, boolean _alarmRaised, u1171639.shared.main.java.corba.models.CorbaModel_Sensor[] _sensors)
  {
    name = _name;
    alarmRaised = _alarmRaised;
    sensors = _sensors;
  } // ctor

} // class CorbaModel_Zone
