package u1171639.shared.main.java.corba.models;


/**
* u1171639/shared/main/java/corba/models/CorbaModel_Log.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Models.idl
* Friday, 15 May 2015 00:04:27 o'clock BST
*/

public final class CorbaModel_Log implements org.omg.CORBA.portable.IDLEntity
{
  public u1171639.shared.main.java.corba.models.CorbaModel_LogItem logItems[] = null;

  public CorbaModel_Log ()
  {
  } // ctor

  public CorbaModel_Log (u1171639.shared.main.java.corba.models.CorbaModel_LogItem[] _logItems)
  {
    this.logItems = _logItems;
  } // ctor

} // class CorbaModel_Log
