package u1171639.shared.main.java.corba.models;


/**
* u1171639/shared/main/java/corba/models/CorbaModel_LogItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Models.idl
* Monday, 20 April 2015 23:09:46 o'clock BST
*/

public final class CorbaModel_LogItem implements org.omg.CORBA.portable.IDLEntity
{
  public String event = null;
  public String message = null;

  public CorbaModel_LogItem ()
  {
  } // ctor

  public CorbaModel_LogItem (String _event, String _message)
  {
    event = _event;
    message = _message;
  } // ctor

} // class CorbaModel_LogItem
