package lms;

/**
* lms/LMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_Sensor.idl
* Thursday, 9 April 2015 17:41:33 o'clock BST
*/

public final class LMSHolder implements org.omg.CORBA.portable.Streamable
{
  public lms.LMS value = null;

  public LMSHolder ()
  {
  }

  public LMSHolder (lms.LMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lms.LMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lms.LMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lms.LMSHelper.type ();
  }

}
