package lms;


/**
* lms/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LMS_Sensor.idl
* Thursday, 9 April 2015 17:41:33 o'clock BST
*/

public interface LMSOperations 
{
  void raiseAlarm (String zone);
  void register (String ior, String zone);
} // interface LMSOperations
