package u1171639.sensor.main.java.corba;


/**
* u1171639/sensor/main/java/corba/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/sensor/main/resources/idl/Sensor.idl
* Sunday, 5 April 2015 01:16:34 o'clock BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
