package u1171639.sensor.main.java.corba;


/**
* u1171639/sensor/main/java/corba/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sensor.idl
* Saturday, 4 April 2015 00:58:01 o'clock BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
