package u1171639.sensor.main.java.corba;

/**
* u1171639/sensor/main/java/corba/SensorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/sensor/main/resources/idl/Sensor.idl
* Wednesday, 22 April 2015 16:43:07 o'clock BST
*/

public final class SensorHolder implements org.omg.CORBA.portable.Streamable
{
  public u1171639.sensor.main.java.corba.Sensor value = null;

  public SensorHolder ()
  {
  }

  public SensorHolder (u1171639.sensor.main.java.corba.Sensor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = u1171639.sensor.main.java.corba.SensorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    u1171639.sensor.main.java.corba.SensorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return u1171639.sensor.main.java.corba.SensorHelper.type ();
  }

}
