package u1171639.sensor.main.java.corba;


/**
* u1171639/sensor/main/java/corba/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sensor.idl
* Saturday, 4 April 2015 00:58:01 o'clock BST
*/

public interface SensorOperations 
{
  boolean isAlarmRaised ();
} // interface SensorOperations
