package u1171639.sensor.main.java.corba;


/**
* u1171639/sensor/main/java/corba/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Workspaces/Eclipse/RiverMonitoringSystem/src/u1171639/sensor/main/resources/idl/Sensor.idl
* Sunday, 5 April 2015 01:16:34 o'clock BST
*/

public interface SensorOperations 
{
  boolean isAlarmRaised ();
  void activate ();
  void deactivate ();
  boolean isActive ();
} // interface SensorOperations
